# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/apple/Downloads/finalproject/interface.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(801, 589)
        MainWindow.setMinimumSize(QtCore.QSize(801, 589))
        MainWindow.setMaximumSize(QtCore.QSize(801, 589))
        MainWindow.setMouseTracking(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.show_img = QtWidgets.QPushButton(self.centralwidget)
        self.show_img.setGeometry(QtCore.QRect(30, 510, 141, 32))
        self.show_img.setObjectName("show_img")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(430, 110, 120, 51))
        self.groupBox.setObjectName("groupBox")
        self.model_box = QtWidgets.QComboBox(self.groupBox)
        self.model_box.setGeometry(QtCore.QRect(0, 15, 121, 41))
        self.model_box.setObjectName("model_box")
        self.model_box.addItem("")
        self.model_box.addItem("")
        self.model_box.addItem("")
        self.model_box.addItem("")
        self.model_box.addItem("")
        self.model_box.addItem("")
        self.model_box.addItem("")
        self.model_box.addItem("")
        self.predict_button = QtWidgets.QPushButton(self.centralwidget)
        self.predict_button.setGeometry(QtCore.QRect(630, 130, 131, 32))
        self.predict_button.setObjectName("predict_button")
        self.output = QtWidgets.QTextBrowser(self.centralwidget)
        self.output.setGeometry(QtCore.QRect(420, 180, 351, 41))
        self.output.setObjectName("output")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(250, 40, 301, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Hebrew Scholar")
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_5.setTextFormat(QtCore.Qt.AutoText)
        self.label_5.setObjectName("label_5")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(20, 260, 361, 241))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.img_label = QtWidgets.QLabel(self.frame)
        self.img_label.setGeometry(QtCore.QRect(10, 10, 341, 221))
        self.img_label.setText("")
        self.img_label.setObjectName("img_label")
        self.hid_img = QtWidgets.QPushButton(self.centralwidget)
        self.hid_img.setGeometry(QtCore.QRect(230, 510, 141, 32))
        self.hid_img.setObjectName("hid_img")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 80, 781, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(390, 120, 20, 411))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(420, 370, 351, 131))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.notebook = QtWidgets.QTextEdit(self.frame_2)
        self.notebook.setGeometry(QtCore.QRect(10, 10, 331, 111))
        self.notebook.setObjectName("notebook")
        self.clear = QtWidgets.QPushButton(self.centralwidget)
        self.clear.setGeometry(QtCore.QRect(10, 180, 61, 71))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.clear.setFont(font)
        self.clear.setAccessibleDescription("")
        self.clear.setInputMethodHints(QtCore.Qt.ImhNone)
        self.clear.setAutoExclusive(True)
        self.clear.setAutoDefault(True)
        self.clear.setDefault(False)
        self.clear.setFlat(False)
        self.clear.setObjectName("clear")
        self.help = QtWidgets.QPushButton(self.centralwidget)
        self.help.setGeometry(QtCore.QRect(10, 100, 61, 71))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.help.setFont(font)
        self.help.setAccessibleDescription("")
        self.help.setInputMethodHints(QtCore.Qt.ImhNone)
        self.help.setAutoExclusive(True)
        self.help.setAutoDefault(True)
        self.help.setDefault(False)
        self.help.setFlat(False)
        self.help.setObjectName("help")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(490, 500, 221, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.filename = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.filename.setObjectName("filename")
        self.horizontalLayout.addWidget(self.filename)
        self.save = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.save.setObjectName("save")
        self.horizontalLayout.addWidget(self.save)
        self.comment = QtWidgets.QTextBrowser(self.centralwidget)
        self.comment.setGeometry(QtCore.QRect(420, 230, 351, 101))
        self.comment.setObjectName("comment")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(430, 350, 60, 16))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.show_img.setText(_translate("MainWindow", "Show Graph"))
        self.groupBox.setTitle(_translate("MainWindow", "Model"))
        self.model_box.setItemText(0, _translate("MainWindow", "None"))
        self.model_box.setItemText(1, _translate("MainWindow", "SVM"))
        self.model_box.setItemText(2, _translate("MainWindow", "LR"))
        self.model_box.setItemText(3, _translate("MainWindow", "KNN"))
        self.model_box.setItemText(4, _translate("MainWindow", "NB"))
        self.model_box.setItemText(5, _translate("MainWindow", "Tree"))
        self.model_box.setItemText(6, _translate("MainWindow", "RF"))
        self.model_box.setItemText(7, _translate("MainWindow", "Boosting"))
        self.predict_button.setText(_translate("MainWindow", "predict"))
        self.output.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.SF NS Text\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.output.setPlaceholderText(_translate("MainWindow", "Output Value Indicator"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; color:#f4150a;\">Credit Risk Predict Tools</span></p></body></html>"))
        self.hid_img.setText(_translate("MainWindow", "Erase"))
        self.notebook.setPlaceholderText(_translate("MainWindow", "Note"))
        self.clear.setText(_translate("MainWindow", "Clear"))
        self.help.setText(_translate("MainWindow", "Help"))
        self.filename.setPlaceholderText(_translate("MainWindow", "File name"))
        self.save.setText(_translate("MainWindow", "Save"))
        self.comment.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.SF NS Text\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.comment.setPlaceholderText(_translate("MainWindow", "Interpretation"))
        self.label.setText(_translate("MainWindow", "Note"))

